version: "3.9"

services:
  app:
    image: ghcr.io/buulka/stripe_test_task:latest
    pull_policy: always
    container_name: app
    ports:
      - "80:80"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - HOST=84.46.240.20
      - STRIPE_KEY=sk_test_51M5dVjB8COH5NDNLlPPOQciEFiLBEZ1k1hks1nHPhWjHMUMkqB346nQpgtNDX015K5e1fZ7fI9MjntVYBLAROxRO00xKW4TX7j
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

volumes:
  db:
