# Generated by Django 4.1.3 on 2022-11-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('coupon_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('output_amount', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Скидки',
                'db_table': 'discounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'db_table': 'items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discount_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stripeApp.discount')),
                ('items', models.ManyToManyField(to='stripeApp.item')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
                'managed': True,
            },
        ),
    ]
