name: 'Main CI'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login --username "$GITHUB_ACTOR" --password "$GITHUB_TOKEN"
      - name: Build container
        run: docker build -t ghcr.io/buulka/stripeTestTask:latest .
      - name: Push container
        run: docker push ghcr.io/buulka/stripeTestTask:latest
