name: 'Main CI'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login --username ${{ github.actor }} --password-stdin ghcr.io
      - name: Build container
        run: docker build -t ghcr.io/buulka/stripeTestTask:latest .
      - name: Push container
        run: docker push ghcr.io/buulka/stripeTestTask:latest
